### ISSUE TITLE
Ability to toggle colourised log output on/off

### ISSUE THREAD

**Issue by janderson2** [ONSdigital/dp-logging#3]
When streaming the logs to file or centralised logging it would be helpful to be able to disable colourised output to avoid the escape sequences in the logs.  It would be very helpful if this could be configured via an environment variable for simplicity and separation of code from environment.

**Comment by daiLlew** [comment]
https://github.com/ONSdigital/dp-logging/pull/5

**Comment by daiLlew** [comment]
redundant - colour logging no supported in v2 impl.
